user_name = input("What is your name? \n")
print('Welcome to the Band name generator ' + user_name + ' !!!!')
city = input("May I know which city you grew up in? \n")
pet_name = input("May I know the name of your pet? \n")
print("Your brand name can be: " + city + pet_name)
